### ISSUE TITLE
Randomly happens com.semmle.util.exception.CatastrophicError: End of file found while looking for '.pop' with a C++ project

### ISSUE THREAD

**Issue by changyuheng** [microsoft/Windows-Driver-Developer-Supplemental-Tools#38]
The symptom is pretty much the same with https://github.com/github/codeql/issues/9929 but the issue does not happen 100% of the time.

CodeQL CLI version: `2.6.3`
CodeQL queries version: `lgtm/1.29.0`
[Windows Driver Developer Supplemental Tools](https://github.com/microsoft/Windows-Driver-Developer-Supplemental-Tools) version: `WHCP_22H2`

```
Finalizing database at C:\Users\user\workspace\ipu-cam-drv-ice-master\camerasw\bins\Release.x64\CodeQL\Database.
ipu_device_ff_properties_impl.h.4f534201.trap (pg_187_control_init.c.86ad7c77_0.trap.tar.br) for 2 link targets, 1605: java.io.IOException: Brotli stream decoding failed
org.brotli.dec.BrotliInputStream.read(BrotliInputStream.java:151)
org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:608)
java.base/java.io.FilterInputStream.read(Unknown Source)
com.semmle.inmemory.trap.TrapInputStream.read(TrapInputStream.java:61)
com.semmle.inmemory.trap.TrapScanner.fill(TrapScanner.java:507)
com.semmle.inmemory.trap.TrapScanner.ensureNext(TrapScanner.java:484)
com.semmle.inmemory.trap.TrapScanner.identOrLabelRest(TrapScanner.java:171)
com.semmle.inmemory.trap.TrapScanner.nextToken(TrapScanner.java:123)
com.semmle.inmemory.trap.TRAPReader.scanTuplesAndLabels(TRAPReader.java:491)
com.semmle.inmemory.trap.TRAPReader.importTuples(TRAPReader.java:423)
com.semmle.inmemory.trap.ImportTasksProcessor.process(ImportTasksProcessor.java:191)
com.semmle.inmemory.trap.ImportTasksProcessor.lambda$null$1(ImportTasksProcessor.java:151)
com.semmle.util.concurrent.FutureUtils.lambda$null$8(FutureUtils.java:136)
java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)

 ... caused by:

org.brotli.dec.BrotliRuntimeException: Invalid backward reference
org.brotli.dec.Decode.decompress(Decode.java:887)
org.brotli.dec.BrotliInputStream.read(BrotliInputStream.java:145)
org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:608)
java.base/java.io.FilterInputStream.read(Unknown Source)
com.semmle.inmemory.trap.TrapInputStream.read(TrapInputStream.java:61)
com.semmle.inmemory.trap.TrapScanner.fill(TrapScanner.java:507)
com.semmle.inmemory.trap.TrapScanner.ensureNext(TrapScanner.java:484)
com.semmle.inmemory.trap.TrapScanner.identOrLabelRest(TrapScanner.java:171)
com.semmle.inmemory.trap.TrapScanner.nextToken(TrapScanner.java:123)
com.semmle.inmemory.trap.TRAPReader.scanTuplesAndLabels(TRAPReader.java:491)
com.semmle.inmemory.trap.TRAPReader.importTuples(TRAPReader.java:423)
com.semmle.inmemory.trap.ImportTasksProcessor.process(ImportTasksProcessor.java:191)
com.semmle.inmemory.trap.ImportTasksProcessor.lambda$null$1(ImportTasksProcessor.java:151)
com.semmle.util.concurrent.FutureUtils.lambda$null$8(FutureUtils.java:136)
java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)
program_psa_out_s2v_dma_control_init.c.e495e4e7.trap (program_psa_out_s2v_dma_control_init.c.e495e4e7_0.trap.tar.br) for 2 link targets, 3669: java.io.IOException: Brotli stream decoding failed
org.brotli.dec.BrotliInputStream.read(BrotliInputStream.java:151)
org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:608)
java.base/java.io.FilterInputStream.read(Unknown Source)
com.semmle.inmemory.trap.TrapInputStream.read(TrapInputStream.java:61)
com.semmle.inmemory.trap.TrapScanner.fill(TrapScanner.java:507)
com.semmle.inmemory.trap.TrapScanner.ensureNext(TrapScanner.java:484)
com.semmle.inmemory.trap.TrapScanner.stringBody(TrapScanner.java:191)
com.semmle.inmemory.trap.TrapScanner.string(TrapScanner.java:224)
com.semmle.inmemory.trap.TrapScanner.nextToken(TrapScanner.java:119)
com.semmle.inmemory.trap.TRAPReader.scanLabelValue(TRAPReader.java:790)
com.semmle.inmemory.trap.TRAPReader.scanTuplesAndLabels(TRAPReader.java:503)
com.semmle.inmemory.trap.TRAPReader.importTuples(TRAPReader.java:423)
com.semmle.inmemory.trap.ImportTasksProcessor.process(ImportTasksProcessor.java:191)
com.semmle.inmemory.trap.ImportTasksProcessor.lambda$null$1(ImportTasksProcessor.java:151)
com.semmle.util.concurrent.FutureUtils.lambda$null$8(FutureUtils.java:136)
java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)

 ... caused by:

org.brotli.dec.BrotliRuntimeException: Corrupted padding bits
org.brotli.dec.BitReader.jumpToByteBoundary(BitReader.java:178)
org.brotli.dec.Decode.decompress(Decode.java:1004)
org.brotli.dec.BrotliInputStream.read(BrotliInputStream.java:145)
org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:608)
java.base/java.io.FilterInputStream.read(Unknown Source)
com.semmle.inmemory.trap.TrapInputStream.read(TrapInputStream.java:61)
com.semmle.inmemory.trap.TrapScanner.fill(TrapScanner.java:507)
com.semmle.inmemory.trap.TrapScanner.ensureNext(TrapScanner.java:484)
com.semmle.inmemory.trap.TrapScanner.stringBody(TrapScanner.java:191)
com.semmle.inmemory.trap.TrapScanner.string(TrapScanner.java:224)
com.semmle.inmemory.trap.TrapScanner.nextToken(TrapScanner.java:119)
com.semmle.inmemory.trap.TRAPReader.scanLabelValue(TRAPReader.java:790)
com.semmle.inmemory.trap.TRAPReader.scanTuplesAndLabels(TRAPReader.java:503)
com.semmle.inmemory.trap.TRAPReader.importTuples(TRAPReader.java:423)
com.semmle.inmemory.trap.ImportTasksProcessor.process(ImportTasksProcessor.java:191)
com.semmle.inmemory.trap.ImportTasksProcessor.lambda$null$1(ImportTasksProcessor.java:151)
com.semmle.util.concurrent.FutureUtils.lambda$null$8(FutureUtils.java:136)
java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: End of file found while looking for '.pop'.
	at com.semmle.inmemory.trap.TRAPReader.importTuples(TRAPReader.java:435)
	at com.semmle.inmemory.trap.ImportTasksProcessor.process(ImportTasksProcessor.java:191)
	at com.semmle.inmemory.trap.ImportTasksProcessor.lambda$null$1(ImportTasksProcessor.java:151)
	at com.semmle.util.concurrent.FutureUtils.lambda$null$8(FutureUtils.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

https://github.com/github/codeql/issues/11586

**Comment by changyuheng** [comment]
Please see my response here: https://github.com/github/codeql/issues/11586#issuecomment-1344006609
Thank you again.
